feat: inference module
PolSl-PBL-7/DragonEye pull request #13
Opened 2021-11-29 12:23 UTC by Fakser

## What type of PR is this?

feature

## What this PR does / why we need it:

This PR introduces inference module, that will be used by inference pipeline to use models, and create anomaly predictions

## Which issue(s) this PR fixes:

Fixes #

## Special notes for your reviewer:

## Additional documentation e.g., enhancement proposals, usage docs, etc.:

2021-11-29 23:46 UTC, damiankucharski approved these changes

2021-11-30 09:49 UTC, Shanduur requested changes
1. Do not comment out CI pipelines.
2. Run `make autopep` to automatically fix most issues that *flake8* will show.

2021-11-30 09:49 UTC, Shanduur commented on Makefile
> +# .PHONY: flake
Do not comment out parts of Makefile, it's unnecessary.

2021-11-30 09:49 UTC, Shanduur commented on .drone.yml
> +# kind: pipeline
The way you commented this file, disabled the whole CI, fix it.

2021-11-30 11:21 UTC, Shanduur submitted a review, later dismissed

2021-11-30 11:37 UTC, arkadiusz-czerwinski approved these changes

2021-11-30 11:54 UTC, arkadiusz-czerwinski approved these changes

2021-11-30 12:32 UTC, Shanduur approved these changes

2021-11-30 12:32 UTC, merged