feat: integrate itae model with our code
PolSl-PBL-7/DragonEye pull request #36
Opened 2022-01-17 21:38 UTC by Fakser

Co-authored-by: Damian Kucharski <c.DamianKucharski@gmail.com>

## What type of PR is this?

## What this PR does / why we need it:

## Which issue(s) this PR fixes:

Fixes #

## Special notes for your reviewer:

## Additional documentation e.g., enhancement proposals, usage docs, etc.:

2022-01-17 21:47 UTC, Shanduur approved these changes

2022-01-23 16:29 UTC, damiankucharski submitted a review, later dismissed

2022-01-23 16:44 UTC, Shanduur commented on inference/predictor.py
> +        except:
Dodaj chociaż `except Exception`, żeby nie łapało interruptów.

2022-01-23 16:45 UTC, Shanduur requested changes
./inference/predictor.py:31:9

2022-01-23 16:52 UTC, arkadiusz-czerwinski submitted a review, later dismissed

2022-01-23 18:57 UTC, Shanduur submitted a review, later dismissed

2022-01-23 19:05 UTC, Shanduur submitted a review, later dismissed

2022-01-23 22:11 UTC, damiankucharski submitted a review, later dismissed

2022-01-24 10:50 UTC, Shanduur approved these changes

2022-01-24 10:53 UTC, damiankucharski approved these changes

2022-01-24 10:54 UTC, merged